############################# Users ##################

# accueil admin

admin_accueil:
    path: /backoffice/accueil
    controller: App\Controller\BackOfficeController::index

# liste users

liste_user:
    path: /backoffice/liste-utilisateur
    controller: App\Controller\BackOfficeController::viewUsers

# Session

inscription_user:
    path: /users/inscription
    controller: App\Controller\UsersController::inscriptionUser

############################# Balades ##################

# Balades

index_balade:
    path: /balades
    controller: App\Controller\BaladesController::indexBalades

add_balade:
    path: /balades/ajouter
    controller: App\Controller\BaladesController::addBalade



############################# Réunions ##################

index_reunions:
    path: /reunions/index
    controller: App\Controller\ReunionsController::indexReunion

view_reunion:
    path: /reunions/details/{id}
    controller: App\Controller\ReunionsController::viewReunion
    requirements:
      id: '\d+' 

add_reunions:
    path: /reunions/ajouter-une-reunion
    controller: App\Controller\ReunionsController::addReunion

edit_reunions:
    path: /reunions/modifier-une-reunion/{id}
    controller: App\Controller\ReunionsController::editReunion
    requirements:
      id: '\d+' 

del_reunions:
    path: /reunions/supprimer-une-reunion/{id}
    controller: App\Controller\ReunionsController::delReunion
    requirements:
      id: '\d+' 

############################# Portfolio ##################

view_portfolio:
    path: /photos/portfolio
    controller: App\Controller\PhotosController::viewPortfolio

############################# Albums ##################

view_albums:
    path: /photos/albums
    controller: App\Controller\PhotosController::viewAlbums