############################# Default ##################

accueil:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

############################# BackOffice ##################

admin_accueil:
    path: /backoffice/accueil
    controller: App\Controller\BackOfficeController::index

liste_user:
    path: /backoffice/liste-utilisateur
    controller: App\Controller\BackOfficeController::viewUsers

############################# Users ##################
inscription_user:
    path: /users/inscription
    controller: App\Controller\UsersController::inscriptionUser

connexion_user:
    path: /users/login
    controller: App\Controller\UsersController::loginUser

deconnexion_user:
    path: /users/logout
    controller: App\Controller\UsersController::logoutUser

forgot_password:
    path: /users/forgot-password
    controller: App\Controller\UsersController::forgotPasswordUser

reinit_password:
    path: /users/reinit-password
    controller: App\Controller\UsersController::reinitPasswordUser

view_profile:
    path: /users/profil
    controller: App\Controller\UsersController::viewProfile

############################# Balades ##################

index_balades:
    path: /balades
    controller: App\Controller\BaladesController::indexBalades

add_balade:
    path: /balades/ajouter
    controller: App\Controller\BaladesController::addBalade

view_balade:
    path: /balades/afficher-une-balade/{id}
    controller: App\Controller\BaladesController::viewBalade
     requirements:
      id: '\d+'

############################# Photos ##################

portfolio:
    path: /portfolio/
    controller: App\Controller\PhotosController::portfolio

view_portfolio:
    path: /photos/portfolio/{id}
    controller: App\Controller\PhotosController::viewPortfolio
    requirements:
      id: '\d+'

view_albums:
    path: /photos/albums
    controller: App\Controller\PhotosController::viewAlbums

add_photo:
    path: /photos/ajouter
    controller: App\Controller\PhotosController::addPhoto


############################# Réunions ##################
add_reunion:
    path: /reunions/ajouter-une-reunion
    controller: App\Controller\ReunionsController::addReunion

index_reunions:
    path: /reunions
    controller: App\Controller\ReunionsController::indexReunion

view_reunion:
    path: /reunions/details/{id}
    controller: App\Controller\ReunionsController::viewReunion
    requirements:
      id: '\d+' 

edit_reunion:
    path: /reunions/modifier-une-reunion/{id}
    controller: App\Controller\ReunionsController::editReunion
    requirements:
      id: '\d+' 

del_reunion:
    path: /reunions/supprimer-une-reunion/{id}
    controller: App\Controller\ReunionsController::delReunion
    requirements:
      id: '\d+'


    #### CR 

add_cr:
    path: /reunions/ajouter-un-cr/{id}
    controller: App\Controller\ReunionsController::addCr
    requirements:
      id: '\d+'

edit_cr:
    path: /reunions/modifier-un-cr/{id}
    controller: App\Controller\ReunionsController::editCr
    requirements:
      id: '\d+'

index_cr:
    path: /reunions/liste-cr
    controller: App\Controller\ReunionsController::indexCr

view_cr:
    path: /reunions/cr-details/{id}
    controller: App\Controller\ReunionsController::viewCr
    requirements:
      id: '\d+' 

del_cr:
    path: /reunions/supprimer-un-cr/{id}
    controller: App\Controller\ReunionsController::delCr
    requirements:
      id: '\d+'
