# Session

inscription_user:
    path: /users/inscription
    controller: App\Controller\UsersController::inscriptionUser

# Balades

add_balade:
    path: /balades/ajouter
    controller: App\Controller\BaladesController::addBalade