# accueil admin

admin_accueil:
    path: /backoffice/accueil
    controller: App\Controller\BackOfficeController::index

# liste users

liste_user:
    path: /backoffice/liste-utilisateur
    controller: App\Controller\BackOfficeController::viewUsers

# Session

inscription_user:
    path: /users/inscription
    controller: App\Controller\UsersController::inscriptionUser

# Balades

add_balade:
    path: /balades/ajouter
    controller: App\Controller\BaladesController::addBalade